### ISSUE TITLE
Add locator delegation

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/interactors#102]
In #90 we added filter delegation, which allows a filter to delegate to another interactor. The same would be useful for locators as well. This requires a bit of rethinking of filters and locators. In my opinion, we should unify filters and locators, and use the same sort of setup for both locators and filters, which would make locator delegation emerge naturally. This probably requires some careful refactoring inside the interactors code base.

**Comment by cowboyd** [comment]
> Is this something we want to do for `v1`? My guess would be "no"?

Not if we think it will be a breaking change. If so, then it would be worth consideration. Otherwise, I'd say let's release 1.0, and then this could be added with a `1.x` release
