### ISSUE TITLE
Slow interactors performance with jsdom

### ISSUE THREAD

**Issue by wKich** [thefrontside/interactors#188]
There is the issue in jsdom https://github.com/jsdom/jsdom/issues/3234 which describes poor performance of `getComputedStyle`. We don't use it directly in interactors, but `isVisible` from https://github.com/thefrontside/element-is-visible does and because `HTML` interactor has `visible: true` filter by default we call isVisible on every element in dom.

As a workaround we can make some tweaks to reduce amount of `getComputedStyle` calls:
- For `exists` method stop finding/executing filters on the first found element
- While finding in the first order apply explicitly defined filters/locator like `Button('Submit', { focused: true })` and then check implicit filters

**Comment by jorgelainfiesta** [comment]
Can I tell the `exists` command to not do the `isVisible` query?

**Comment by wKich** [comment]
@jorgelainfiesta the only thing you can do is like extend from `Button` interactor and override `visible` filter, something like this

```ts
const MyButton = Button.filters({
  visible: Button().options.specification.filters.visible.apply
})
```

But, let's check how it will go after those workarounds.

**Comment by cowboyd** [comment]
We've done about all we can do with #190 Can we close this?

**Comment by cowboyd** [comment]
Closing since this has been resolved (mostly)
