### ISSUE TITLE
buggy @testing-library/dom v8.18.0 should be avoided

### ISSUE THREAD

**Issue by zburke** [thefrontside/interactors#212]
## Summary

In `@interactors/core`, the minimum version of `@testing-library/dom` should be bumped from `^8.5.0` to `^8.18.1` in order to guarantee avoiding the buggy `8.18.0` release. 

## Details
The v8.18.0 release of [@testing-library/dom](https://github.com/testing-library/dom-testing-library/) doesn't play nice with Cypress due to testing-library/dom-testing-library/issues/1169. Test failures may look like this:

> The error was:Error: Webpack Compilation Error./node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js 429:27Module parse failed: Unexpected token (429:27)You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders%7C   // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition -- types are not aware of older browsers that don't implement `labels`|   if (element.labels !== undefined) {>     return element.labels ?? [];|   }|  @ ./node_modules/@testing-library/user-event/dist/click.js 9:11-42

The bug was patched in `8.18.1`, which is what `@interactors/core` _should_ receive based on its [`^8.5.0` dep](https://github.com/thefrontside/interactors/blob/c5c32b9615d3a975050124bd7da331e12d2161ed/packages/core/package.json#L38) if yarn/npm and semver do their job. Of course, yarn and npm aren't always reliable, or use caches, etc. Thus, it would be helpful to bump the minimum version from `^8.5.0` to `^8.18.1`; it's semver-compatible with `^8.5.0` but avoids the buggy `8.18.0` release.

**Comment by cowboyd** [comment]
@zburke it's is now released 👍
