### ISSUE TITLE
Link broken : https://frontside.com/interactors/docs/existing-interactors#material-ui

### ISSUE THREAD

**Issue by dkoul** [thefrontside/interactors#232]

**Comment by cowboyd** [comment]
Hi @dkoul! Thanks for taking the time to report this. What page did you find this broken link on?

**Comment by dkoul** [comment]
Sorry about not sharing the url earlier, this page, https://frontside.com/interactors/mui/api/index.html, last link

**Comment by cowboyd** [comment]
@dkoul Thanks, we'll get that fixed. In the mean time, this is the url it should go to https://frontside.com/interactors/docs/library#material-ui
