### ISSUE TITLE
Interactors don't work after updating to Cypress 12

### ISSUE THREAD

**Issue by ostapwd** [thefrontside/interactors#234]
![image](https://github.com/thefrontside/interactors/assets/18191661/c3dd6ebc-9151-4504-9247-ea180a14aefc)

**Comment by cowboyd** [comment]
Hi @ostapwd. Thanks for reporting this. Can you create a small repository that recreates this issue? This would be very helpful in tracking this down /cc @wKich

**Comment by wKich** [comment]
It seems Cypress did something with built-in commands, this might be related with https://github.com/cypress-io/cypress/issues/22733
