### ISSUE TITLE
Allow accepting a regular expression inside an interactor constructor?

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/interactors#26]
RTL allows you to pass either a string on a regular expression when searching for an element on the page:

```js
await screen.getElementByText(/submit/i)
```

We can do the same, but it requires explicitly using the `matching` matcher:

```js
await Button(matching(/submit/i)).exists();
```

Should we just do a check in the constructor and if it is an instance of regular expression, use the matching matcher automatically? That way, you could just say:

```js
await Button(/submit/i).exists();
```

**Comment by wKich** [comment]
I agree with @cowboyd, that improve DX a little
