### ISSUE TITLE
Should we use `main` as the default branch here?

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/interactors#27]
We have `@interactors/html` which is about to go 1.0, but we also will be bringing in, `@interactors/material-ui` which will be at version 4.0 in order to track semver releases of `material-ui` which is currently at v4. When v5 is released, we will need to make that package also v5.

It seems like all the different versions of interactors in this package will have their own semver schedules, and so having a single one for the entire repo may not make as much sense.

**Comment by minkimcello** [comment]
That makes sense to me, i'll create a PR
