### ISSUE TITLE
import `material-ui-interactors` as `@interactors/material-ui`

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/interactors#28]
It can be imported at version 4.

**Comment by minkimcello** [comment]
Just leaving this here as a reminder to myself.

I'm currently finishing up the rough draft to introduce mui in the interactors docs in [this](https://github.com/thefrontside/bigtest/pull/995) PR. When we move `material-ui-interactors` into this repository, we should remember to update the docs too.

**Comment by cherewaty** [comment]
We skipped this step.
