### ISSUE TITLE
Function innerText(element) in @interactors/html/esm/src/html.js spot working after the latest changes

### ISSUE THREAD

**Issue by ostapwd** [thefrontside/interactors#304]
After the recent changes function **innerText(element)** in @interactors/html/esm/src/html.js stopped working in **Cypress**
We are getting the following message
![image](https://github.com/user-attachments/assets/16ed429d-1ff6-42ea-bc51-8fe945ebc14d)
![image](https://github.com/user-attachments/assets/1ba0b3f0-3de3-45d7-80ad-ee2465ddf893)

**Comment by ostapwd** [comment]
Updates: after a short investigation I figured out the issue relates to **Optional chaining**. For some reason, it doesn't work in many places
![image](https://github.com/user-attachments/assets/a9ddb2e6-613d-480b-9746-3414f6b08990)
![image](https://github.com/user-atta
![image](https://github.com/user-attachments/assets/5fe06ae9-7908-4788-822c-c824111bc787)
chments/assets/3ad6a5c7-983d-428e-9475-d0a7c775c04b)

**Comment by ostapwd** [comment]
Updates: after googling I found the following:
https://stackoverflow.com/questions/72937510/unexpected-token-chaining-operator-expression-when-cypress-filepreprocessor-rea
The solution to this error is to configure browserify-preprocessor for cypress. The default options for browserify are applaying ES2020 features.

trying to do this

**Comment by ostapwd** [comment]
Installing **@cypress/webpack-preprocessor** with default configuration solved the issue
https://www.npmjs.com/package/@cypress/webpack-preprocessor?activeTab=readme
![image](https://github.com/user-attachments/assets/ef6f76e8-e1e4-4c4b-8ccf-980b25c1fd3e)

**Comment by cowboyd** [comment]
Does your target browser support `?` chaining?

**Comment by ostapwd** [comment]
yes, we are using Chrome
btw I switched to **@cypress/webpack-batteries-included-preprocessor** instead of **@cypress/webpack-preprocessor** (there were some issues with path resolving), pass-rate is better, but anyway, we can see some strange issues
![image](https://github.com/user-attachments/assets/75b95519-3bcc-43b7-9876-47be1a179939)
![image](https://github.com/user-attachments/assets/2b57e1b4-fa70-4409-ac9e-6d9cca48a4e3)

**Comment by cowboyd** [comment]
@ostapwd Was there a definitive fix for this? The only thing that should have changed between `v1.0.0` and `v1.0.1` is that we tried to change the structure of the NPM package to be more friendly to typescript and ESM modules. There were no changes to the actual source code itself.
